volumes:
  db:

services:
  db:
    image: postgres:17.2
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    restart: on-failure

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure
